import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 6, y = 6 }
opacity = 0.72
option_as_alt = "Both"

[font]
# normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
normal = { family = "MesloLGM Nerd Font" }
size = 12

[cursor]
style = { shape = "Underline", blinking = "Always" }
# style = { shape = "Beam", blinking = "Always" }

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
